[project]
name = "llmfiles"
version = "0.2.0"
description = "Intelligently build LLM prompts from codebases, git info, and templates."
readme = "README.md"
requires-python = ">=3.11" 
license = { text = "Apache-2.0" }
authors = [
    { name = "Fred Bliss"}, 
]
classifiers = [ # Standard trove classifiers for PyPI
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Build Tools",
    "Topic :: Utilities",
    "Environment :: Console", # Indicates it's a command-line application
    "Intended Audience :: Developers",
]
dependencies = [
    "click>=8.0",         # For building the command-line interface
    "pathspec>=0.11",     # For .gitignore style pattern matching
    "pybars3>=0.9",       # Handlebars templating engine
    "tiktoken>=0.5",      # For OpenAI token counting
    "pyperclip>=1.8",     # For clipboard operations (copying output)
    "rich>=13.0",
    "PyYAML>=5.0",
]

[project.optional-dependencies]
dev = ["pytest>=7.0", "pytest-cov"]

[project.scripts]
llmfiles = "llmfiles.cli:main_cli_entrypoint"

[project.urls] # Useful links related to the project
Homepage = "https://github.com/fblissjr/llmfiles"

[build-system] # Standard PEP 517 build system configuration
requires = ["hatchling"] # Specifies Hatchling as the build backend
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["llmfiles"]

[tool.rye]
managed = true # Indicates Rye manages this project
dev-dependencies = [
    "pytest>=7.0",
    "pytest-cov"
]

[tool.pytest.ini_options]
pythonpath = ["."]
addopts = "-v --cov=llmfiles --cov-report=term-missing"